# ============================================================================
#
# update_version.ps1 - Update the MMDD date portion of the version in PaDDY
# Copyright (c) NoID Softwork 2026-2026. All rights reserved.
#
# Version format: a.b.c.MMDD
#   a    = Frontend update (GUI)
#   b    = Backend update
#   c    = Little fix / patch
#   MMDD = Month and day of push (auto-generated by this script)
#
# Usage:
#   .\update_version.ps1
#   (Reads current a.b.c from PaDDY.csproj, updates MMDD to today, saves back)
# ============================================================================

$repoRoot          = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectFilePath   = Join-Path $repoRoot "PaDDY.csproj"
$assemblyInfoPath  = Join-Path $repoRoot "AssemblyInfo.cs"

function Update-ProjectVersionDate {
    param(
        [string]$ProjectPath,
        [string]$NewVersion
    )

    if (-not (Test-Path $ProjectPath)) {
        Write-Host "Project not found: $ProjectPath" -ForegroundColor Yellow
        return
    }

    [xml]$projectFile = Get-Content $ProjectPath
    $projectFile.Project.PropertyGroup.Version         = $NewVersion
    $projectFile.Project.PropertyGroup.AssemblyVersion = $NewVersion
    $projectFile.Project.PropertyGroup.FileVersion     = $NewVersion
    $projectFile.Save($ProjectPath)

    Write-Host "Version updated: $ProjectPath -> $NewVersion" -ForegroundColor Green
}

# Read current version from PaDDY.csproj
if (-not (Test-Path $projectFilePath)) {
    Write-Host "[ERROR] PaDDY.csproj not found at: $projectFilePath" -ForegroundColor Red
    exit 1
}

[xml]$mainProjectFile = Get-Content $projectFilePath
$currentVersion = $mainProjectFile.Project.PropertyGroup.Version

if (-not $currentVersion) {
    Write-Host "[ERROR] No <Version> element found in PaDDY.csproj" -ForegroundColor Red
    exit 1
}

Write-Host "Current version: $currentVersion" -ForegroundColor White

$versionParts = $currentVersion -split '\.'
while ($versionParts.Count -lt 3) { $versionParts += "0" }

$a = [int]$versionParts[0]
$b = [int]$versionParts[1]
$c = [int]$versionParts[2]

$today      = Get-Date
$dateString = $today.ToString("MMdd")
$newVersion = "$a.$b.$c.$dateString"

Write-Host "New version:     $newVersion" -ForegroundColor Cyan

# Update PaDDY.csproj
Update-ProjectVersionDate -ProjectPath $projectFilePath -NewVersion $newVersion

# Update AssemblyInfo.cs
if (Test-Path $assemblyInfoPath) {
    $assemblyInfoContent = Get-Content $assemblyInfoPath -Raw -Encoding UTF8

    $assemblyInfoContent = $assemblyInfoContent -replace '\[assembly: AssemblyVersion\("[^"]*"\)\]',               "[assembly: AssemblyVersion(""$newVersion"")]"
    $assemblyInfoContent = $assemblyInfoContent -replace '\[assembly: AssemblyFileVersion\("[^"]*"\)\]',           "[assembly: AssemblyFileVersion(""$newVersion"")]"
    $assemblyInfoContent = $assemblyInfoContent -replace '\[assembly: AssemblyInformationalVersion\("[^"]*"\)\]',  "[assembly: AssemblyInformationalVersion(""$newVersion"")]"

    # Append attributes if missing
    if ($assemblyInfoContent -notmatch 'AssemblyVersion') {
        $assemblyInfoContent += "`r`n[assembly: AssemblyVersion(""$newVersion"")]"
    }
    if ($assemblyInfoContent -notmatch 'AssemblyFileVersion') {
        $assemblyInfoContent += "`r`n[assembly: AssemblyFileVersion(""$newVersion"")]"
    }
    if ($assemblyInfoContent -notmatch 'AssemblyInformationalVersion') {
        $assemblyInfoContent += "`r`n[assembly: AssemblyInformationalVersion(""$newVersion"")]"
    }

    Set-Content -Path $assemblyInfoPath -Value $assemblyInfoContent -Encoding UTF8
    Write-Host "AssemblyInfo.cs updated with version: $newVersion" -ForegroundColor Green
} else {
    Write-Host "[WARNING] AssemblyInfo.cs not found at: $assemblyInfoPath" -ForegroundColor Yellow
}

Write-Host "`n[DONE] Version updated to $newVersion" -ForegroundColor Cyan
