//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaDDY.Resources {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaDDY.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName => ResourceManager.GetString("AppName", resourceCulture) ?? "PaDDY";
        public static string Close => ResourceManager.GetString("Close", resourceCulture) ?? "Close";
        public static string Save => ResourceManager.GetString("Save", resourceCulture) ?? "Save";
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "Cancel";
        public static string OK => ResourceManager.GetString("OK", resourceCulture) ?? "OK";
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture) ?? "Delete";
        public static string Edit => ResourceManager.GetString("Edit", resourceCulture) ?? "Edit";
        public static string Apply => ResourceManager.GetString("Apply", resourceCulture) ?? "Apply";
        public static string Search => ResourceManager.GetString("Search", resourceCulture) ?? "Search";
        public static string Default => ResourceManager.GetString("Default", resourceCulture) ?? "Default";
    }
}
