<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NoIDSoftwork.EffectProcessor</AssemblyName>
    <RootNamespace>NoIDSoftwork.EffectProcessor</RootNamespace>
    <Description>NoIDSoftwork.EffectProcessor</Description>
    <Product>NoIDSoftwork.EffectProcessor</Product>
    <Company>NoID Softwork</Company>
    <Copyright>Copyright (c) NoID Softwork 2020-2026. All rights reserved.</Copyright>
    <Version>2.4.0.0828</Version>
    <AssemblyVersion>2.4.0.0828</AssemblyVersion>
    <FileVersion>2.4.0.0828</FileVersion>
    <InformationalVersion>2.4.0.0828-Pre-release_1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Plugins\VST2\mdaDe-ess.dll">
      <LogicalName>Plugins.VST2.mdaDe-ess.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Plugins\VST2\mdaDynamics.dll">
      <LogicalName>Plugins.VST2.mdaDynamics.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Plugins\VST3\WetReverb.vst3\Contents\x86_64-win\WetReverb.vst3">
      <LogicalName>Plugins.VST3.WetReverb.vst3</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>